# frontend/Dockerfile
FROM node:20-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps
RUN npm install typescript@5.5.4 --save-dev --legacy-peer-deps
COPY . .
RUN npm run build:prod

FROM node:20-alpine
RUN npm install -g serve
COPY --from=build /app/dist/guilda-social-frontend /app
WORKDIR /app
EXPOSE 80
CMD ["serve", "-s", ".", "-l", "80"]
