# frontend/Dockerfile

# Estágio 1: Build
FROM node:20-alpine AS build

WORKDIR /app

# Copiar arquivos de configuração
COPY package.json package-lock.json ./
RUN npm ci --legacy-peer-deps
RUN npm install typescript@5.5.4 --save-dev --legacy-peer-deps

# Copiar angular.json com budgets ajustados
COPY angular.json ./
COPY tsconfig.json ./
COPY tsconfig.app.json ./

# Copiar código fonte
COPY src ./src

# Build da aplicação
RUN npm run build:prod

# Estágio 2: Servir com serve
FROM node:20-alpine
RUN npm install -g serve
COPY --from=build /app/dist/guilda-social-frontend /app
WORKDIR /app
EXPOSE 80
CMD ["serve", "-s", ".", "-l", "80"]
